// api/recommend.js
// POST { read_history, onboarding_genres, currently_reading, shown_books }
// Returns { rows: [{ label, kind: "taste"|"discovery", recommendations: [{ book, reason, confidence }] }] }
//
// Deploy target: Vercel. Runtime: Node.js serverless function.
// Env var required: ANTHROPIC_API_KEY (set in Vercel project settings, never in code).

import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// How many book-metadata lookups run at once. Bounded rather than unlimited
// so we don't blast Google Books with 15-24 simultaneous requests and invite
// rate-limiting — 5 is enough to turn ~20-30s of serial lookups into a few
// seconds without leaning on it too hard.
const LOOKUP_CONCURRENCY = 5;

async function mapWithConcurrency(items, limit, mapper) {
  const results = new Array(items.length);
  let nextIndex = 0;
  async function worker() {
    while (nextIndex < items.length) {
      const current = nextIndex++;
      results[current] = await mapper(items[current], current);
    }
  }
  const workers = Array.from({ length: Math.min(limit, items.length) }, worker);
  await Promise.all(workers);
  return results;
}

// Each row is generated by its own, independent Claude call, run concurrently
// with the other two (see generateRow/ROW_ASSIGNMENTS below) — this lets
// total generation time scale with the slowest single row instead of the sum
// of all three, and means one row's call failing doesn't take the other two
// down with it. Each call only knows about its own assignment, not what the
// other two calls are producing, so cross-row duplicate books are caught
// afterward (see dedup pass in the handler) rather than avoided up front.
const BASE_SYSTEM_PROMPT = `You are the recommendation engine for Dogear, a reading app.
You are generating ONE row of a multi-row Today feed — two other rows are being generated
in parallel by separate calls that you can't see, so focus only on the row assignment
below rather than trying to cover the reader's whole taste in this one row.

Reader history uses shelf placement instead of star ratings — treat these as the real
signal, not a proxy for one:
- "keepForever" = their strongest possible endorsement, weight heavily.
- "gladIReadIt" = solid but not formative — mild positive signal.
- "shouldveStopped" = a real negative signal (they regret finishing it) — actively avoid
  whatever made this book similar to others, don't just ignore it.
A book currently being read with "still_enjoying_midpoint": false is an early warning —
treat it like a soft negative signal even though it's not finished yet.

Recency: read_history and currently_reading are both ordered most-recent-first. Weight
recent shelf placements more heavily than old ones — a reader's taste shifts over time,
and their last few books say more about what to recommend next than their first few. If
the recent entries trend toward a different tone, genre, or pace than the older history,
follow that recent trend rather than averaging it in with everything that came before.

Rules:
- Never recommend a book already in their read history.
- Never recommend a book listed in shown_books, even if it would otherwise be a strong
  pick. shown_books is every book already surfaced to this reader by this endpoint or by
  vibe search, whether or not they saved it — it's a hard exclusion, just like read_history.
- Prefer specificity over safety: real, findable, in-print books only. No invented titles.
- Return 4-6 books for this row.
- "reason" must be one sentence, written directly to the reader ("you"), naming the
  specific pattern that earned this pick. No generic praise ("a wonderful read").
- confidence is your own calibrated 0.0-1.0 estimate of fit, used only for sort order —
  never shown to the user verbatim, so don't hedge it, just be honest.
- "label" must be specific and honest, written as if a bookseller were handing over a
  stack: "Because you loved Beloved," "More slow-burn sci-fi like The Left Hand of
  Darkness." Never a generic label like "More fiction" or "You might also like."

Return ONLY valid JSON matching this exact shape, nothing else — no markdown fences,
no preamble:
{
  "label": "string",
  "recommendations": [
    {
      "title": "string",
      "author": "string",
      "reason": "string",
      "confidence": 0.0
    }
  ]
}`;

const ROW_ASSIGNMENTS = [
  {
    kind: "taste",
    instruction: `ROW ASSIGNMENT: primary taste row. Ground it in the single most
dominant, clearest pattern in the reader's history — their strongest keepForever book,
or if read_history is empty, the first onboarding genre. This should be the most
obvious, highest-confidence row.`,
  },
  {
    kind: "taste",
    instruction: `ROW ASSIGNMENT: secondary taste row. Ground it in a genuinely
DIFFERENT pattern from the reader's history than their single most obvious one — a
different book, author, or facet of their taste (pacing, subject, structure). If
read_history is empty, ground this in a different onboarding genre than the most
obvious pick. If the history doesn't support a truly distinct second pattern, explore a
different facet of the same overall taste rather than forcing an unrelated pick — but
favor genuine difference when it exists.`,
  },
  {
    kind: "discovery",
    instruction: `ROW ASSIGNMENT: discovery row. Every pick must intentionally step
outside the reader's established pattern — adjacent but genuinely new (a neighboring
genre, an unfamiliar structure or era) — never just a repeat of their usual taste with a
different label. This row exists to stretch the reader, not to hedge. Frame the label
explicitly as something different, e.g. "Something a little different tonight."`,
  },
];

async function generateRow(assignment, historyText) {
  const userContent = `${historyText}\n\n${assignment.instruction}`;
  const claudeStart = Date.now();
  const msg = await anthropic.messages.create({
    model: "claude-sonnet-5",
    max_tokens: 1500,
    system: BASE_SYSTEM_PROMPT,
    messages: [{ role: "user", content: userContent }],
  });
  const claudeMs = Date.now() - claudeStart;

  const raw = msg.content.find((b) => b.type === "text")?.text ?? "{}";
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (parseErr) {
    console.error(`Failed to parse ${assignment.kind} row response:`, parseErr.message, "raw:", raw);
    throw parseErr;
  }

  return {
    kind: assignment.kind,
    label: parsed.label,
    recommendations: parsed.recommendations ?? [],
    claudeMs,
  };
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "POST only" });
  }

  if (req.headers["x-app-secret"] !== process.env.APP_SHARED_SECRET) {
    return res.status(401).json({ error: "unauthorized" });
  }

  const { read_history, onboarding_genres, currently_reading, shown_books } = req.body ?? {};
  if (!Array.isArray(read_history)) {
    return res.status(400).json({ error: "read_history must be an array" });
  }

  const historyText = read_history.length
    ? JSON.stringify({
        read_history,
        currently_reading: currently_reading ?? [],
        shown_books: shown_books ?? [],
        note: "read_history and currently_reading are ordered most-recent-first."
      }, null, 2)
    : JSON.stringify({
        onboarding_genres: onboarding_genres ?? [],
        shown_books: shown_books ?? [],
        note: "No finished books yet — ground taste rows in these genres and still " +
              "include one discovery row, excluding anything in shown_books."
      }, null, 2);

  try {
    // Three independent Claude calls in parallel — one per row — instead of
    // one call generating the whole taxonomy. Promise.allSettled so one
    // row's call failing (parse error, API hiccup) doesn't take the other
    // two down with it; we return whatever succeeded rather than 500ing the
    // whole feed over one row.
    const settled = await Promise.allSettled(
      ROW_ASSIGNMENTS.map((assignment) => generateRow(assignment, historyText))
    );

    const successfulRows = [];
    settled.forEach((result, i) => {
      if (result.status === "fulfilled") {
        successfulRows.push(result.value);
      } else {
        console.error(`Row ${i} (${ROW_ASSIGNMENTS[i].kind}) failed:`, result.reason?.message);
      }
    });

    if (successfulRows.length === 0) {
      throw new Error("all three row generations failed");
    }

    // Independent calls can't see each other's picks — dedup across rows now,
    // keeping the first occurrence (primary taste, then secondary, then
    // discovery) and dropping later repeats. A shorter row is preferable to
    // showing the same book twice, same principle as shown_books exclusion.
    const seenKeys = new Set();
    const dedupedRows = successfulRows
      .map((row) => {
        const kept = row.recommendations.filter((rec) => {
          const key = `${(rec.title ?? "").toLowerCase()}|${(rec.author ?? "").toLowerCase()}`;
          if (seenKeys.has(key)) return false;
          seenKeys.add(key);
          return true;
        });
        return { ...row, recommendations: kept };
      })
      .filter((row) => row.recommendations.length > 0);

    // Flatten across the surviving rows so metadata lookups run with bounded
    // concurrency over the whole response, not serially.
    const flat = [];
    dedupedRows.forEach((row, rowIndex) => {
      row.recommendations.forEach((rec) => flat.push({ rowIndex, rec }));
    });

    const lookupStart = Date.now();
    const enrichedFlat = await mapWithConcurrency(flat, LOOKUP_CONCURRENCY, async ({ rec }) => {
      const book = await safeLookupBook(rec.title, rec.author);
      return { book, reason: rec.reason, confidence: rec.confidence ?? 0.5 };
    });
    const lookupMs = Date.now() - lookupStart;

    const rowBuckets = dedupedRows.map(() => []);
    enrichedFlat.forEach((enriched, i) => {
      rowBuckets[flat[i].rowIndex].push(enriched);
    });

    const rows = dedupedRows.map((row, i) => ({
      label: row.label,
      kind: row.kind,
      recommendations: rowBuckets[i],
    }));

    const claudeMaxMs = Math.max(...successfulRows.map((r) => r.claudeMs));
    console.log(
      `recommend timing: claudeMax=${claudeMaxMs}ms lookup=${lookupMs}ms ` +
      `books=${flat.length} rowsOK=${successfulRows.length}/3`
    );

    return res.status(200).json({ rows });
  } catch (err) {
    console.error("recommend error:", err);
    return res.status(500).json({ error: "recommendation failed" });
  }
}

// Decision #21 reliability fix: a single book's metadata lookup failing (Google
// Books timeout, malformed response, etc.) must never take down the whole
// request. lookupBook()/tryGoogleBooksQuery() already degrade internally
// (Google -> Open Library -> bare fallback), but this is the last line of
// defense for anything that still throws unexpectedly.
async function safeLookupBook(title, author) {
  try {
    return await lookupBook(title, author);
  } catch (err) {
    console.error("lookupBook failed unexpectedly, using bare fallback:", title, author, err?.message);
    return {
      id: `${title}-${author}`.replace(/\s+/g, "-").toLowerCase(),
      title,
      author,
      coverURL: null,
      pageCount: null,
      genres: [],
      summary: null,
    };
  }
}

async function lookupBook(title, author) {
  const key = process.env.GOOGLE_BOOKS_API_KEY;
  const keyParam = key ? `&key=${key}` : "";

  let item = await tryGoogleBooksQuery(
    `intitle:${title} inauthor:${author}`,
    keyParam
  );
  if (!item) {
    item = await tryGoogleBooksQuery(`${title} ${author}`, keyParam);
  }

  if (item) {
    const info = item.volumeInfo;
    return {
      id: item.id,
      title: info?.title ?? title,
      author: info?.authors?.[0] ?? author,
      coverURL: info?.imageLinks?.thumbnail?.replace(/^http:/, "https:") ?? null,
      pageCount: info?.pageCount ?? null,
      genres: info?.categories ?? [],
      summary: info?.description ?? null,
    };
  }

  // Google's Books API has been intermittently failing entirely (backendFailed
  // 503s) — fall back to Open Library, which needs no API key and has its own
  // large, independent catalog and cover-image service.
  return lookupOpenLibrary(title, author);
}

async function lookupOpenLibrary(title, author) {
  try {
    const q = encodeURIComponent(`${title} ${author}`);
    const resp = await fetch(
      `https://openlibrary.org/search.json?q=${q}&limit=1`
    );
    const data = await resp.json();
    const doc = data.docs?.[0];

    return {
      id: doc?.key ?? `${title}-${author}`.replace(/\s+/g, "-").toLowerCase(),
      title: doc?.title ?? title,
      author: doc?.author_name?.[0] ?? author,
      coverURL: doc?.cover_i
        ? `https://covers.openlibrary.org/b/id/${doc.cover_i}-L.jpg`
        : null,
      pageCount: doc?.number_of_pages_median ?? null,
      genres: doc?.subject?.slice(0, 3) ?? [],
      summary: null,
    };
  } catch (err) {
    console.error("Open Library lookup failed:", err);
    return {
      id: `${title}-${author}`.replace(/\s+/g, "-").toLowerCase(),
      title,
      author,
      coverURL: null,
      pageCount: null,
      genres: [],
      summary: null,
    };
  }
}

// Decision #21: wrap the actually-flaky call (Google Books has shown
// intermittent backendFailed 503s and outright request failures) in its own
// try/catch with one retry before giving up and letting lookupBook() fall
// through to Open Library. Previously this fetch was unguarded — a thrown
// error here propagated all the way out of the per-book loop and failed the
// entire recommend() request over a single cover lookup.
async function tryGoogleBooksQuery(query, keyParam, attempt = 0) {
  const q = encodeURIComponent(query);
  const url = `https://www.googleapis.com/books/v1/volumes?q=${q}&maxResults=1${keyParam}`;
  try {
    const resp = await fetch(url);
    const data = await resp.json();
    if (data.error) {
      console.error("Google Books error for query:", query, JSON.stringify(data.error));
      return null;
    }
    return data.items?.[0] ?? null;
  } catch (err) {
    if (attempt === 0) {
      console.error("Google Books fetch failed, retrying once:", query, err?.message);
      return tryGoogleBooksQuery(query, keyParam, attempt + 1);
    }
    console.error("Google Books fetch failed after retry, falling back:", query, err?.message);
    return null;
  }
}
